version: "3"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    deploy:
      resources:
        reservations:
          cpus: '2'
          memory: 2GB
    environment:
      SA_PASSWORD: "myPassword1"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql

  web-app:
    image: danieiihomiesscr.azurecr.io/homies
    ports:
      - "80:80"
    restart: always

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: homiesdanielstorageacc
