services:
  vote:
    image: vote
    ports:
      - "5000:80"
    networks:
      - frontend
      - backend

  result:
    image: result
    command: nodemon server.js
    ports:
      - "5001:80" 
    networks:
      - frontend
      - backend

  worker:
    image: worker
    networks:
        - backend

  redis:
    image: redis
    networks:
        - backend

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - backend
    volumes:
      - db:/var/lib/postgresql


volumes:
  db:
networks:
  frontend:
  backend:
