version: "3"

services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "data:/data/db"

  backend:
    depends_on: ["mongodb"]
    image: "danieii/goals-backend"
    ports:
      - "80:80"
    volumes:
      - "logs:/app/logs"
      - "node_modules:/app/node_modules"

  frontend:
    depends_on: ["backend"]
    image: "danieii/goals-frontend"
    ports:
      - "3000:3000"
    volumes:
      - "./frontend/src/:/app/src"
  
volumes:
  data:
  logs:
  node_modules:
